# Generated by Django 2.2.6 on 2020-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TvShow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='seriesImage',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dizinin Resmini Ekleyin'),
        ),
    ]
